language: php
php:
  - 5.4
env:
  - KOHANA_ENV=TESTING
branches:
  only:
    - master
    - develop
services:
  - mongodb
before_script:
  - ./.travis-mongo-php.sh
before_install:
  - git submodule update --init --recursive
  - cd application/tests
